################################################################################
#
# GLOBAL OPTIONS
#
################################################################################

# Specify how ochami should log
log:
  # Log level. Specify how verbose ochami should be. Available values are:
  #
  # info
  # warning (default)
  # debug
  level: warning

  # Log format. Specify the format of log messages. Available values are:
  #
  # json    - Log fields in JSON format
  # rfc3339 - Follows formatting in RFC 3339 (default)
  # basic   - Specifies log level but no timestamp data
  format: rfc3339

# Specify the name of the cluster to use by default. If this is not specified,
# --cluster must be used on the command line to specify the name of the cluster
# to use when communicating with OpenCHAMI services.
#
# The directive below is commented out in case this file is used as an actual
# config file.
#default-cluster: local

################################################################################
#
# CLUSTER-SPECIFIC OPTIONS
#
################################################################################

# The clusters block specify a list of cluster configurations that can be used
# by ochami. Each item in the cluster list has the following keys:
#
# name    - The user-defined name of the cluster. This is what is used by
#           default-cluster above and --cluster on the CLI.
# cluster - The block containing the actual cluster configuration.
#
# The cluster block can contain the following keys:
#
# ca-cert - Path to certificate authority certificate to use to verify TLS
#           certificates.
#
# uri - The base URI of all OpenCHAMI services. ochami will append the base path
#       and endpoint to this URI. If uri is specified in any of the <service>
#       configs below, this behavior changes (see '<service>' below).
#
#       If uri is not specified, then <service>.uri directives must be specified
#       for each <service>.
#
# <service> - (OPTIONAL) Set specific service options for <service>. <service>
#             is the name of an OpenCHAMI service in lower case, e.g. 'bss',
#             'cloud-init'.
#
#             Keys include:
#
#             uri - Override the service's base path or replace its base URI
#                   entirely. If the value is a relative path (e.g. "/smd"),
#                   this path replace the service's default base path, which is
#                   what is appended to cluster.uri when communicating with the
#                   service. If the value is an absolute URI (e.g. https://...),
#                   then this value replaces that of the appendix of cluster.api
#                   and the service base path. In other words, the value becomes
#                   the base URI specifically for this service.
#
#                   Specifying this option is optional if cluster.uri is
#                   specified, but mandatory for each service if not. If
#                   cluster.uri is specified, this can be used to override
#                   either the base path or entire base URI for this service.
#
# Below is an example of a clusters block, commented out in case this
# file is used as an actual config.
#
#clusters:
#    - name: foobar
#      cluster:
#        uri: https://foobar.openchami.cluster
#    - name: local
#      cluster:
#        uri: https://local.openchami.cluster:8443
#
# An example of overriding the SMD path from the default /hsm/v2 to /smd and
# overriding the entire URI for BSS (all other services are left to their
# defaults):
#
#clusters:
#    - name: foobar
#      cluster:
#        uri: https://foobar.openchami.cluster:8443
#        smd:
#          uri: /smd
#        bss:
#          uri: https://bss.my.cluster/boot/v1
#
# Another example omitting cluster.uri entirely, using separate <service>.uri
# directives:
#
#clusters:
#    - name: foobar
#      cluster:
#        smd:
#          uri: https://localhost:27779/hsm/v2
#        bss:
#          uri: https://localhost:27778/boot/v1
#        cloud-init:
#          uri: https://localhost:27777/cloud-init
#        pcs:
#          uri: https://localhost:28007
clusters: []
