# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V.
# SPDX-License-Identifier: CC0-1.0
name: REUSE compliance check
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - name: REUSE Compliance Check
        run: pipx run --backend pip --spec reuse==6.2.0 reuse lint --lines
